# These are supported funding model platforms

# patreon: marcuwynu23
# open_collective: marcuwynu23
# ko_fi: marcuwynu23
# tidelift: # Replace with tidelift name
# community_bridge: # Replace with community bridge name
# liberapay: # Replace with liberapay username
# issuehunt: # Replace with issuehunt username
# otechie: # Replace with otechie username
custom: [ "https://paypal.me/wynumarcu23" ]
